services:
  - type: web
    name: rizky-mengalir
    rootDir: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
